# Netlify configuration for Astro hybrid site
[build]
  publish = "dist"
  command = "npm run build"

# Enable Netlify dev for local development
[dev]
  framework = "astro"
  command = "npm run dev"

# Handle 404s properly by redirecting to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
